# Generated by Django 5.2.14 on 2026-06-01 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='leaveapp_le_status_16aab8_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee'], name='leaveapp_le_employe_272006_idx'),
        ),
    ]
